export const SERVER_DEAL_HAND = 'SERVER_DEAL_HAND';
export const SERVER_ADD_CARD_TO_IN_PLAY = 'SERVER_ADD_CARD_TO_IN_PLAY';
export const SERVER_ADD_CARDS_TO_PLAYED = 'SERVER_ADD_CARDS_TO_PLAYED';

export const CLIENT_UPDATE_STORE = 'CLIENT_UPDATE_STORE';
