export const SERVER_RESET_GAME = 'SERVER_RESET_GAME';
export const SERVER_DEAL_HAND = 'SERVER_DEAL_HAND';
export const SERVER_ADD_CARD_TO_IN_PLAY = 'SERVER_ADD_CARD_TO_IN_PLAY';
export const SERVER_ADD_CARDS_TO_PLAYED = 'SERVER_ADD_CARDS_TO_PLAYED';
export const SERVER_CHANGE_USER_NAME = 'SERVER_CHANGE_USER_NAME';
export const SERVER_ALLOCATE_USER_TO_PLAYER = 'SERVER_ALLOCATE_USER_TO_PLAYER';
export const SERVER_DEALLOCATE_USER_TO_PLAYER = 'SERVER_DEALLOCATE_USER_TO_PLAYER';

export const CLIENT_UPDATE_STORE = 'CLIENT_UPDATE_STORE';
export const CLIENT_TOAST_MESSAGE = 'CLIENT_TOAST_MESSAGE';
